/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: taj_tajima (https://sketchfab.com/taj_tajima)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zaku-ii-730a08b171aa4ac0a43131752150acfb
Title: Zaku II
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Zaku_ii = (props) => {
  const { nodes, materials } = useGLTF('models/zaku_ii.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.m_14}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/zaku_ii.glb')

export default Zaku_ii;
